USE Libreria
GO

IF OBJECT_ID('dbo.AUTOR') IS NULL
BEGIN
CREATE TABLE AUTOR (
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(200) NOT NULL,
	PRIMER_APELLIDO VARCHAR(200) NOT NULL,
	SEGUNO_APELLIDO VARCHAR(200)
);
END

IF OBJECT_ID('dbo.GENERO') IS NULL
BEGIN
CREATE TABLE GENERO (
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(200) NOT NULL
);
END

IF OBJECT_ID('dbo.PAIS') IS NULL
BEGIN
CREATE TABLE PAIS(
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(200) NOT NULL
);
END

IF OBJECT_ID('dbo.EDITORIAL') IS NULL
BEGIN
CREATE TABLE EDITORIAL (
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(200) NOT NULL,
	ID_PAIS INT NOT NULL,
	FECHA DATETIME	
);

ALTER TABLE dbo.EDITORIAL
ADD CONSTRAINT FK_PAIS_EDITORIAL
FOREIGN KEY(ID_PAIS) REFERENCES dbo.PAIS (ID);

END

IF OBJECT_ID('dbo.LIBRO') IS NULL
BEGIN
CREATE TABLE LIBRO (
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(200) NOT NULL,
	ID_AUTOR INT NOT NULL,
	ID_GENERO INT NOT NULL,
	COSTO DECIMAL NOT NULL,
	FECHA_PUBLICACIÓN DATETIME NOT NULL,
	ID_EDITORIAL INT NOT NULL,
	CANTIDAD_PAGINAS INT, 
	TIPO_EDICION VARCHAR(200),
	ESTADO VARCHAR(200) NOT NULL		
);

ALTER TABLE dbo.LIBRO
ADD CONSTRAINT FK_AUTOR_LIBRO
FOREIGN KEY(ID_AUTOR) REFERENCES dbo.AUTOR (ID);

ALTER TABLE dbo.LIBRO
ADD CONSTRAINT FK_GENERO_LIBRO
FOREIGN KEY(ID_GENERO) REFERENCES dbo.GENERO (ID)

ALTER TABLE dbo.LIBRO
ADD CONSTRAINT FK_EDITORIAL_LIBRO
FOREIGN KEY(ID_EDITORIAL) REFERENCES dbo.EDITORIAL (ID)
END


