USE Libreria
GO
IF OBJECT_ID('dbo.TIPO') IS NULL
BEGIN
	CREATE TABLE TIPO(
		IDTIPO INT IDENTITY(1,1) PRIMARY KEY,
		NOMBRE VARCHAR(250) NOT NULL
	)
END

IF OBJECT_ID('dbo.EDITORIAL_MARCA_SELLO') IS NULL
BEGIN
	CREATE TABLE EDITORIAL_MARCA_SELLO(
		IDEDSEMA INT IDENTITY(1,1) PRIMARY KEY,
		NOMBRE VARCHAR(200) NOT NULL
	)
END

IF OBJECT_ID('dbo.EDIMARCASELLO_TIPO') IS NULL
BEGIN
	CREATE TABLE EDIMARCASELLO_TIPO(
		IDEDSEMA INT NOT NULL,
		IDTIPO INT NOT NULL	
	)

	ALTER TABLE dbo.EDIMARCASELLO_TIPO
	ADD CONSTRAINT FK_EDIMARCASELLOTIPO_IDEDSEMA
	FOREIGN KEY(IDEDSEMA) REFERENCES dbo.EDITORIAL_MARCA_SELLO(IDEDSEMA)

	ALTER TABLE dbo.EDIMARCASELLO_TIPO
	ADD CONSTRAINT FK_EDIMARCASELLOTIPO_IDTIPO
	FOREIGN KEY(IDTIPO) REFERENCES dbo.TIPO(IDTIPO)
END


IF OBJECT_ID('dbo.PRODUCTO') IS NULL
BEGIN
	CREATE TABLE PRODUCTO(
		IDPRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
		NOMBRE VARCHAR(250) NOT NULL,
		AUTOR VARCHAR(250) NOT NULL,
		IDTIPO INT NOT NULL,
		PRECIO DECIMAL NOT NULL,
		FECHAPUBLICACION DATE NOT NULL,
		IDEDSEMA INT NOT NULL
	)

	ALTER TABLE dbo.PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_TIPO
	FOREIGN KEY(IDTIPO) REFERENCES dbo.TIPO(IDTIPO)

	ALTER TABLE dbo.PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_IDEDSEMA
	FOREIGN KEY(IDEDSEMA) REFERENCES dbo.EDITORIAL_MARCA_SELLO(IDEDSEMA)
END

IF OBJECT_ID('dbo.INVENTARIO') IS NULL
BEGIN
	CREATE TABLE INVENTARIO(
		ID INT IDENTITY(1,1) PRIMARY KEY,
		IDPRODUCTO INT NOT NULL,
		CANTIDAD INT NOT NULL
	)

	ALTER TABLE dbo.INVENTARIO
	ADD CONSTRAINT FK_PRODUCTO_INVENTARIO
	FOREIGN KEY(IDPRODUCTO) REFERENCES dbo.PRODUCTO(IDPRODUCTO)
END

IF OBJECT_ID('dbo.CLIENTE') IS NULL
BEGIN
	CREATE TABLE CLIENTE(
		IDENTCLIENTE INT NOT NULL PRIMARY KEY,
		NOMBRE VARCHAR(250) NOT NULL,
		PRIAPELLIDO VARCHAR (100) NOT NULL,
		SEGAPELLIDO  VARCHAR (100) NULL,
		TELEFONO VARCHAR(10) NOT NULL,
		DIRECCION VARCHAR(100) NOT NULL
	)
END

IF OBJECT_ID('dbo.COMPRAS_CLIENTE') IS NULL
BEGIN
	CREATE TABLE COMPRAS_CLIENTE(
		IDREGISTROCLIENTE INT IDENTITY(1,1) PRIMARY KEY,
		IDENTCLIENTE INT NOT NULL,
		CANTIDADCOMPRAS INT NOT NULL
	)

	ALTER TABLE dbo.COMPRAS_CLIENTE
	ADD CONSTRAINT FK_COMPRAS_CLIENTE_CLIENTE
	FOREIGN KEY(IDENTCLIENTE) REFERENCES dbo.CLIENTE(IDENTCLIENTE)
END

IF OBJECT_ID('dbo.FACTURAVENTA') IS NULL
BEGIN
	CREATE TABLE FACTURAVENTA(
		NUMEROFACTURA INT PRIMARY KEY,
		IDENTCLIENTE INT NOT NULL,
		COSTOTOTAL DECIMAL NOT NULL,
		FECHAFACTURA DATE NOT NULL  
	)

	ALTER TABLE dbo.FACTURAVENTA
	ADD CONSTRAINT FK_FACTURA_CLIENTE
	FOREIGN KEY (IDENTCLIENTE) REFERENCES dbo.CLIENTE (IDENTCLIENTE)
END

IF OBJECT_ID('dbo.FACTURA_PRODUCTO') IS NULL
BEGIN
	CREATE TABLE FACTURA_PRODUCTO(
		NUMEROFACTURA INT NOT NULL,
		IDPRODUCTO INT NOT NULL,
		CANTIDAD INT NOT NULL
	)

	ALTER TABLE dbo.FACTURA_PRODUCTO
	ADD CONSTRAINT FK_FACTPROD_FACT
	FOREIGN KEY (NUMEROFACTURA) REFERENCES dbo.FACTURAVENTA (NUMEROFACTURA)
	
	ALTER TABLE dbo.FACTURA_PRODUCTO
	ADD CONSTRAINT FK_FACTPROD_PROD
	FOREIGN KEY (IDPRODUCTO) REFERENCES dbo.PRODUCTO (IDPRODUCTO)
END

IF OBJECT_ID('dbo.PROMOCION') IS NULL
BEGIN
	CREATE TABLE PROMOCION(
		IDPROMO INT IDENTITY(1,1) PRIMARY KEY,
		IDTIPO INT NOT NULL,
		IDEDSEMA INT NOT NULL,
		FECHAINICIO DATETIME NOT NULL,
		FECHAFIN DATETIME NOT NULL,
		DESCUENTO INT NOT NULL,
		ESTADO BIT NOT NULL		
	)

	ALTER TABLE dbo.PROMOCION
	ADD CONSTRAINT FK_PROMO_TIPO
	FOREIGN KEY (IDTIPO) REFERENCES dbo.TIPO (IDTIPO)
	
	ALTER TABLE dbo.PROMOCION
	ADD CONSTRAINT FK_PROMO_IDEDSEMA
	FOREIGN KEY (IDEDSEMA) REFERENCES dbo.EDITORIAL_MARCA_SELLO (IDEDSEMA)
END
GO


